### PR TITLE
dev: vsc-micro-state and various bindings

### PR DESCRIPTION
**Pull request by lverweijen**
- New layer vcs-micro-state
- Various other bindings

It is recommended that the user put the following in their vimrc:
        let g:gitgutter_map_keys=0

Maybe this can also be done in bootstrap.

### CODE REVIEW

**Comment by ctjhoa** [comment]
Could you rename the vim leader guide category to `vcs-micro-state` ?

**Comment by ctjhoa** [comment]
Why not put `let g:gitgutter_map_keys=0` in `plugin/spacevim.vim` like `vim-leader-guide` conf ?
And override the variable if it's not set of course.

**Comment by lverweijen** [comment]
> Why not put let g:gitgutter_map_keys=0 in plugin/spacevim.vim like vim-leader-guide conf ?
> And override the variable if it's not set of course.

We can try, but it will only work if spacevim is loaded before gitgutter. If we can all agree that the order in which plugins should be loaded: is leaderguide -> spacevim -> everything else, this works reliably. Otherwise the behaviour might be surprising.

It can also be put in autoload/bootstrap. Then it works out of the box for "distribution mode", but "advanced mode" requires this extra line.

**Comment by ctjhoa** [comment]
Hum that's weird ...
In `plugin/spacevim.vim` I've add a custom banner for `vim-startify` and my banner appears  when I launch vim.
When I take a look at `:scriptnames`, `vim-startify` is started before `spacevim` so the banner should not be mine. Do you have any clue?

To be sure we can create a new function in `autoload/spacevim.vim` to override plugin's config.
Or maybe we can take advantage of `vim-plug` order to load `spacevim` first.

**Comment by ctjhoa** [comment]
According to https://github.com/junegunn/vim-plug/issues/85, load order of plugins is deterministic so I'll load spacevim first.

**Comment by lverweijen** [comment]
Gitgutter now disables keybindings if layer vcs-micro-state or help-highlight is enabled.

**Comment by ctjhoa** [comment]
The new release 2.0.0 include all this work. Thanks for your time & investment.

**Pull request closed without merging**
