### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by WuTheFWasThat**
- syntactic integration
- easymotion as replacement for avy
- undo tree
- git gutter
- recommend delimitMate and vim-surround
- improve commentary a bit
- updated readme

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
here are some improvements i made in my fork.  feel free to take just some of the commits, and i'll rebase or whatever

**Comment by ctjhoa** [comment]
@WuTheFWasThat Thanks for your awesome work! I've done a lot of work lately to be more flexible and less plugin dependent in the `dev` branch. I've backport most of your improvements. Just a question how did you get the `highlight-persist-remove-all` in spacemacs I can't find this mapping?

**Comment by WuTheFWasThat** [comment]
not sure - i'm just on commit 9c7250a of spacemacs and it's there

**Comment by WuTheFWasThat** [comment]
I checked out your dev branch - i like the spacevim functions!  and i think people will definitely appreciate how different plugins are supported for the same functionality

will syntastic be ported?  I would rather use your repo than mine, but I can't do without the linting!  also, I'd prefer to use master instead of dev heh - when do you think things will be merged?

some nitpicks, btw:
- you should mention Ag.vim in the README (used for smart-search, <leader>/ )
- right now, j= uses the mark z, but 'ij' and 'ik' use the mark a.  better to only take up one mark!
- why isn't easy-motion between <leader>x and <leader>z?  i noticed the 'fe' bindings are also slightly out of order

**Comment by ctjhoa** [comment]
@WuTheFWasThat 

> you should mention Ag.vim in the README (used for smart-search, / )

No it's just an `fzf.vim` function (fzf is godlike https://github.com/junegunn/fzf.vim#commands) so no need for Ag.vim dependency but could be an alternative.

> right now, j= uses the mark z, but 'ij' and 'ik' use the mark a. better to only take up one mark!

Yeah you're right. I don't know if there is some recommended mark for those cases

> why isn't easy-motion between x and z? i noticed the 'fe' bindings are also slightly out of order

My bad ... bad habits to code until 2am :P

**Comment by WuTheFWasThat** [comment]
Oh, time to delete Ag from my vimrc.. all hail fzf!

**Comment by WuTheFWasThat** [comment]
is ProjectRoot also optional, i think?  

incsearch and over-line are awesome, btw, seems like i won't really need `<leader>sc` much anymore anyways

**Comment by ctjhoa** [comment]
ProjectRoot is optional. For now, it's use only for `project-directory`.

I have found the mystery behind the missing `<leader>sc` in my spacemacs, it's because I've excluded `evil-search-highlight-persist`. Anyway I have backport all your stuff and it's now on master tell me what you think of the new `smart-search-with-input`

**Comment by WuTheFWasThat** [comment]
i've switched to your master now 👍 

smart-search is great!  i didn't even realize that was part of spacemacs, but i'm gonna use it now for sure

**Pull request closed without merging**
