### PR TITLE
SPC w c -> SPC w d

### PR DESCRIPTION
**Pull request by adrianstaniec**
change in spacemacs

### CODE REVIEW

**Comment by ctjhoa** [comment]
I've got the `105.21` version of spacemacs and the shorcut is still SPC w c. What version of spacemacs do you have?

**Comment by adrianstaniec** [comment]
I am using the develop branch :)

**Comment by ctjhoa** [comment]
develop branch is not supported now cause a lot of things change in this branch.
I don't know yet how to migrate to the new shorcuts.
I'll think about it and close this for now. Thanks anyway.

**Comment by adrianstaniec** [comment]
this shortcut is now in master branch :]

**Comment by ctjhoa** [comment]
Yeah I know I have to do some work to support the new `0.200.X` spacemacs. I reopen this and I'll merge it when I'll work to implement the new shorcuts

**Comment by ctjhoa** [comment]
I have fixed this in `dev`  branch

**Pull request closed without merging**
