### PR TITLE
Update PLUGINS.md

### PR DESCRIPTION
**Pull request by WuTheFWasThat**
<leader>fL seems to use ":Locate" which I think comes from here

### CODE REVIEW

**Comment by ctjhoa** [comment]
No that's not that plugin which provide `:Locate`.
Actually 2 plugins comes with this command:
https://www.reddit.com/r/vim/comments/4l9p1c/deal_with_conflict_command/

Ideally, I should deal with conflict by introducing a prefix to fzf (`g:fzf_command_prefix = 'Fzf`) but I don't know where this should be implemented (user space, plugin space) as it's very impacting for spacevim users.

**Comment by WuTheFWasThat** [comment]
ah ok, sorry, shouldve looked into it more.  actually i even have Locate, so I'm not sure why I thought it was missing.  

that said, <leader>fL didn't work for me at all.  does it work for you?  
no big deal for me though, since with find-files (ff) and project-find-file (pf) i'll rarely use it anyways.
I think I'll make <leader>fl be like :e and <leader>fL be :e!

**Comment by ctjhoa** [comment]
What do you mean by `fL didn't work for me at all`? In my case, I don't have the [GNU locate](http://man7.org/linux/man-pages/man1/locate.1.html) installed on my OS so this command return:
```
zsh:1: command not found: locate

Press ENTER or type command to continue
```
but it should work fine if you have installed [findutils](https://www.gnu.org/software/findutils/) or something similar.

**Comment by WuTheFWasThat** [comment]
for me it just does nothing.  if I just do `:Locate<CR>`, it says `E471: Argument required`, which is probably why.  If i if I just do `:Locate sometext<CR>`, stuff happens

edit: also, `:help Locate` shows that it's using vim-eunuch's function.  reordering eunuch and fzf doesnt change that fact

**Comment by ctjhoa** [comment]
Oh yeah that's the intended behavior as it's the [vim-eunuch](https://github.com/tpope/vim-eunuch)'s Locate it's absolutely not interactive.
The fzf version should be more useful but as I said I need too prevent conflict first.

**Comment by WuTheFWasThat** [comment]
ok - it's not just non-interactive, but I don't even get a chance to enter an argument when using `<leader>fL`.  by the way, i think the fzf version actually seems to require an argument as well

**Pull request closed without merging**
