### PR TITLE
make bd not close the current window

### PR DESCRIPTION
**Pull request by WuTheFWasThat**
the functions should maybe be renamed, feel free to modify

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
and apparently needs to be linted :)

**Comment by ctjhoa** [comment]
Could you use https://github.com/moll/vim-bbye instead. I mean add it as plugin. I don't want to have big copy paste of existing plugin. And vim-bbye seems to be  maintained.

**Comment by WuTheFWasThat** [comment]
should be better now!  i should've tried to find that

**Comment by ctjhoa** [comment]
Thanks!

**Pull request merged**
